import type { Metadata } from "next";
import { Asta_Sans, Copse } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/ui/navbar";

const fontSans = Asta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Copse({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang='en' className={`${fontSans.variable} ${fontHeading.variable}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
